USE TECSUP;

INSERT INTO ALUMNOS (NOMBRE, EDAD ) VALUES ("Jose",18);
INSERT INTO ALUMNOS (NOMBRE, EDAD ) VALUES ("Pedro",20);
INSERT INTO ALUMNOS (NOMBRE, EDAD ) VALUES ("Julio",19);
INSERT INTO ALUMNOS (NOMBRE, EDAD ) VALUES ("Alberto",18);
INSERT INTO ALUMNOS (NOMBRE, EDAD ) VALUES ("Jordan",19);